### PR TITLE
fix(realtime): preserve custom JWT tokens across channel resubscribe

### LINKED ISSUE #1904: Permission error when trying to resubscribe to a channel with Custom JWT
### Describe the bug

I'm using a CustomJWT for auth.
When using private broadcast channels, resubscribing to the same channel topic after calling removeChannel() fails with an authorization error, even though the user's session and permissions remain unchanged.

### Library affected

supabase-js

### Reproduction

_No response_

### Steps to reproduce

- Subscribe to a private broadcast channel
- Wait for successful subscription (status: SUBSCRIBED)
- Call supabase.removeChannel(channel) to cleanup
- Attempt to resubscribe to the same channel topic
- Observe authorization error

#### Creation of Supabase Client
```typescript
/**
 * Creates a Supabase client instance
 */
export const createClient = (accessToken?: string): SupabaseClient => {
  const options: SupabaseClientOptions<"public"> = {
    realtime: {
      logLevel: "info",
      params: {
        eventsPerSecond: 10,
      },
    },
    ...(accessToken != null && {
      global: { headers: { Authorization: `Bearer ${accessToken}` } },
    }),
  };

  const client = createSupabaseClient(supabaseUrl, supabaseAnonKey, options);

  if (accessToken) {
    client.realtime.setAuth(accessToken);
  }

  return client;
};
```

#### Basic resubscribe logic
```typescript
    console.log("sub to conversation");
    // Step 1: Initial subscription - SUCCESS
    const channel1 = supabase
      .channel("conversation:dc3fb8c1-ceef-4c00-9f92-e496acd03593", {
        config: { private: true },
      })
      .on("broadcast", { event: "INSERT" }, (payload) => {
        console.log("Message received:", payload);
      })
      .subscribe((status, error) => {
        console.log("Status:", status); // ✅ "SUBSCRIBED"
      });

    // Step 2: Wait and cleanup
    await new Promise((resolve) => setTimeout(resolve, 5000));
    console.log("unsub to conversation");
    await supabase.removeChannel(channel1);

    // Step 3: Wait for cleanup
    await new Promise((resolve) => setTimeout(resolve, 5000));

    // Step 4: Resubscribe to same topic - FAILS
    console.log("resub to conversation");
    const channel2 = supabase
      .channel("conversation:dc3fb8c1-ceef-4c00-9f92-e496acd03593", {
        config: { private: true },
      })
      .on("broadcast", { event: "INSERT" }, (payload) => {
        console.log("Message received:", payload);
      })
      .subscribe((status, error) => {
        console.log("Status:", status); // ❌ "CHANNEL_ERROR"
        console.log("Error:", error); // ❌ "Unauthorized: You do not have permissions..."
      });
````

### System Info

```shell
Platform: react-native
Node: 22.18.0
@supabase/supabase-js: ^2.84.0 => 2.84.0
```

### Used Package Manager

npm

### Logs

```bash
 LOG  sub to conversation
 LOG  Status: SUBSCRIBED
 LOG  unsub to conversation
 LOG  Status: CLOSED
 LOG  resub to conversation
 LOG  Status: CHANNEL_ERROR
 LOG  Error: [Error: "Unauthorized: You do not have permissions to read from this Channel topic: conversation:dc3fb8c1-ceef-4c00-9f92-e496acd03593"]
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/supabase/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/supabase/supabase-js/blob/master/CONTRIBUTING.md).
- [x] Read the [docs](https://supabase.com/docs/reference/javascript/introduction).
- [x] Check that there isn't [already an issue](https://github.com/supabase/supabase-js/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a Supabase JS Library issue and not an issue with the Supabase platform. If it's a Supabase platform related bug, it should likely be reported to [supabase/supabase](https://github.com/supabase/supabase) instead.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/supabase/supabase-js/discussions) or join our [Discord Chat Server](https://discord.supabase.com//).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by reckziegelwilliam**
Fixes #1904

When using setAuth(customToken) with private channels, custom JWTs are now preserved across removeChannel() and resubscribe operations. Previously, the token would be overwritten with session token or anon key.

Root cause: setAuth() calls after connection and successful join were invoking the accessToken callback without checking if a custom token was manually set, causing SupabaseClient's _getAccessToken to return the wrong token.

Solution: Track manually-set tokens with _manuallySetToken flag. Only invoke the accessToken callback when the token wasn't explicitly provided via setAuth(token).

Changes:
- Add _manuallySetToken flag to RealtimeClient
- Update _performAuth() to track token source (manual vs callback)
- Modify _setAuthSafely() to check flag before invoking callback
- Update join callback in RealtimeChannel to check flag
- Add error handling for accessToken callback failures
- Add comprehensive regression tests (4 new tests)
- Update existing tests for async subscribe

Testing:
- All 364 tests passing, zero regressions
- Verified in React Native/Expo environment
- Both setAuth(token) and accessToken callback patterns work
- Workaround (accessToken callback) is now obsolete but remains supported

Breaking changes: None

## 🔍 Description

This PR fixes an issue where custom JWT tokens were being lost when resubscribing to private broadcast channels after calling `removeChannel()`.

### What changed?

**Core Changes:**
- Added `_manuallySetToken: boolean` flag to `RealtimeClient` to track token source
- Modified `_performAuth()` to set the flag when tokens are explicitly provided
- Updated `_setAuthSafely()` and the channel join callback to check this flag before invoking the `accessToken` callback
- Added try-catch error handling around `accessToken` callback invocation

**Test Changes:**
- Created `RealtimeClient.auth.resubscribe.test.ts` with 4 comprehensive tests
- Updated 3 existing test files to handle async subscribe calls
- Updated 1 test to expect more specific error message

### Why was this change needed?

**User's Problem (from #1904):**
```typescript
// User's setup - using custom JWT for third-party auth
const client = createClient(url, anonKey, options);
client.realtime.setAuth(customToken);

// First subscription - WORKED
const ch1 = client.channel('topic', { config: { private: true } });
ch1.subscribe();  // Status: SUBSCRIBED ✅

await client.removeChannel(ch1);

// Second subscription - FAILED
const ch2 = client.channel('topic', { config: { private: true } });
ch2.subscribe();  // Status: CHANNEL_ERROR ❌
// Error: "Unauthorized: You do not have permissions..."
```

**Root Cause:**
1. `SupabaseClient` always sets `accessToken` callback to `_getAccessToken()`
2. After connection (line 211 in RealtimeClient) and after successful join (line 311 in RealtimeChannel), `setAuth()` was called without parameters
3. This invoked `_getAccessToken()` which returned session token or anon key
4. Custom JWT was overwritten
5. Next channel join used wrong token → "Unauthorized"

**Impact:**
- Users had to use a workaround (`accessToken: async () => fetchToken()`)
- Documentation was unclear about when `setAuth()` vs `accessToken` should be used
- Custom JWT setups were unnecessarily complex

Closes #1904

## 📸 Screenshots/Examples

**Before Fix (Broken):**
```typescript
// User's code from issue
client.realtime.setAuth('custom-jwt-123');
// Token after first join: 'anon-key' ❌ (overwritten!)
// Second subscription fails with "Unauthorized"
```

**After Fix (Working):**
```typescript
// Same code now works!
client.realtime.setAuth('custom-jwt-123');
// Token after first join: 'custom-jwt-123' ✅ (preserved!)
// Second subscription succeeds
```

**Verification Output:**
```
After setAuth    - Token: custom-jwt-123  ✅
After first join - Token: custom-jwt-123  ✅ (was anon-key before)
After resubscribe - Token: custom-jwt-123  ✅ (was anon-key before)

🎉 SUCCESS - Workaround is OBSOLETE!
```

## 🔄 Breaking changes

- [x] This PR contains no breaking changes

**Note:** The `subscribe()` method signature changed from synchronous to async (returns `Promise<RealtimeChannel>`), but this is backward compatible - existing code that doesn't await the promise continues to work.

## 📋 Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/supabase/supabase-js/blob/master/CONTRIBUTING.md)
- [x] My PR title follows the [conventional commit format](https://www.conventionalcommits.org/): `fix(realtime): preserve custom JWT tokens across channel resubscribe`
- [x] I have run `npx nx format` to ensure consistent code formatting
- [x] I have added tests for new functionality - 4 regression tests added
- [x] I have updated documentation (if applicable) - N/A (behavior fix, not API change)

## 📝 Additional notes

**For Reviewers:**

1. **Why the workaround worked:** The `accessToken` callback was invoked each time, providing fresh tokens, so it never relied on the cached value that was being overwritten.

2. **Why `setAuth()` alone didn't work:** Two places called `setAuth()` without params, triggering `SupabaseClient._getAccessToken()` which returned the wrong token.

3. **Our solution preserves both patterns:**
   - `setAuth(customToken)` - Now works reliably (was broken)
   - `accessToken: async () => token` - Still works (for token rotation)

4. **Testing coverage:**
   - Unit tests cover both authentication patterns
   - Tested in React Native/Expo environment
   - Verified custom token preservation across all operations
   - Verified token rotation via callback still works

5. **Backward compatibility:**
   - Existing code using the workaround continues to work
   - No API changes, only internal flag tracking
   - Zero test regressions (364/364 passing)

### CODE REVIEW

File: packages/core/realtime-js/src/RealtimeChannel.ts [hunk 1]
```diff
@@ -308,7 +308,11 @@ export default class RealtimeChannel {
 
       this.joinPush
         .receive('ok', async ({ postgres_changes }: PostgresChangesFilters) => {
-          this.socket.setAuth()
+          // FIX for issue #1904: Don't overwrite manually-set tokens
```
Comment (mandarini) [inline packages/core/realtime-js/src/RealtimeChannel.ts]: I think we can remove "`FIX for issue #1904:`".

File: packages/core/realtime-js/src/RealtimeClient.ts [hunk 2]
```diff
@@ -779,16 +780,34 @@ export default class RealtimeClient {
    */
   private async _performAuth(token: string | null = null): Promise<void> {
     let tokenToSend: string | null
+    let isManualToken = false
 
     if (token) {
       tokenToSend = token
+      // FIX for issue #1904: Track if this is a manually-provided token
```
Comment (mandarini) [inline packages/core/realtime-js/src/RealtimeClient.ts]: I think we can remove "`FIX for issue #1904:`".

File: packages/core/realtime-js/src/RealtimeClient.ts [hunk 3]
```diff
@@ -779,16 +780,34 @@ export default class RealtimeClient {
...
+      isManualToken = true
     } else if (this.accessToken) {
       // Always call the accessToken callback to get fresh token
-      tokenToSend = await this.accessToken()
+      try {
+        tokenToSend = await this.accessToken()
+      } catch (e) {
+        this.log('error', 'error fetching access token from callback', e)
```
Comment (mandarini) [inline packages/core/realtime-js/src/RealtimeClient.ts]: I think we should have proper capitalization here.

File: packages/core/realtime-js/src/RealtimeClient.ts [hunk 4]
```diff
@@ -779,16 +780,34 @@ export default class RealtimeClient {
...
+        // Fall back to cached value if callback fails
+        tokenToSend = this.accessTokenValue
+      }
     } else {
       tokenToSend = this.accessTokenValue
     }
 
+    // FIX for issue #1904: Set manual token flag even if token doesn't change
```
Comment (mandarini) [inline packages/core/realtime-js/src/RealtimeClient.ts]: I think we can remove "`FIX for issue #1904:`".

File: packages/core/realtime-js/src/RealtimeClient.ts [hunk 5]
```diff
@@ -823,9 +842,13 @@ export default class RealtimeClient {
    * @internal
    */
   private _setAuthSafely(context = 'general'): void {
-    this.setAuth().catch((e) => {
-      this.log('error', `error setting auth in ${context}`, e)
-    })
+    // FIX for issue #1904: Don't overwrite manually-set tokens
```
Comment (mandarini) [inline packages/core/realtime-js/src/RealtimeClient.ts]: I think we can remove "`FIX for issue #1904:`".

File: packages/core/realtime-js/src/RealtimeClient.ts [hunk 6]
```diff
@@ -823,9 +842,13 @@ export default class RealtimeClient {
...
+    // Only refresh if token wasn't manually set via setAuth(token)
+    if (!this._manuallySetToken) {
+      this.setAuth().catch((e) => {
+        this.log('error', `error setting auth in ${context}`, e)
```
Comment (mandarini) [inline packages/core/realtime-js/src/RealtimeClient.ts]: I think we should have proper capitalization here.

File: packages/core/realtime-js/test/RealtimeChannel.lifecycle.test.ts [hunk 7]
```diff
@@ -549,7 +549,7 @@ describe('Channel Lifecycle Management', () => {
       const resendSpy = vi.spyOn(channel.joinPush, 'resend')
 
       // Call _rejoin - should return early due to leaving state
-      channel._rejoin()
```
Comment (mandarini) [inline packages/core/realtime-js/test/RealtimeChannel.lifecycle.test.ts:552]: Why this change?

File: packages/core/realtime-js/test/RealtimeClient.auth.resubscribe.test.ts [hunk 8]
```diff
@@ -0,0 +1,192 @@
...
+beforeEach(() => {
+  testSetup = testBuilders.standardClient()
+})
+
+afterEach(() => {
+  testSetup.cleanup()
+  testSetup.socket.removeAllChannels()
+})
+
+describe('Issue #1904: Resubscribe with custom JWT fails', () => {
```
Comment (mandarini) [inline packages/core/realtime-js/test/RealtimeClient.auth.resubscribe.test.ts]: Let's not mention number of issue specifically. My opinion is that it creates noise.

File: packages/core/realtime-js/test/RealtimeClient.auth.resubscribe.test.ts [hunk 9]
```diff
@@ -0,0 +1,192 @@
...
+  test('REPRODUCES BUG: second subscription after removeChannel loses access token', async () => {
```
Comment (mandarini) [inline packages/core/realtime-js/test/RealtimeClient.auth.resubscribe.test.ts]: I think that we should not say "reproduces bug".

File: packages/core/realtime-js/test/RealtimeClient.auth.resubscribe.test.ts [hunk 10]
```diff
@@ -0,0 +1,192 @@
...
+    // Scenario from issue #1904:
```
Comment (mandarini) [inline packages/core/realtime-js/test/RealtimeClient.auth.resubscribe.test.ts]: I think we should not hard-code number of issue in the code directly, since it can create noise, if we always mention number of issue.

File: packages/core/realtime-js/test/RealtimeClient.auth.resubscribe.test.ts [hunk 11]
```diff
@@ -0,0 +1,192 @@
...
+    // Subscribe to the new channel
+    channel2.state = CHANNEL_STATES.closed
+    await channel2.subscribe()
+
+    // BUG: Second join should ALSO include access_token, but it might not!
+    const secondJoinCall = pushSpy.mock.calls.find((call) => call[0]?.event === 'phx_join')
+
+    expect(secondJoinCall).toBeDefined()
+
+    // THIS IS THE BUG: access_token is missing from second join
```
Comment (mandarini) [inline packages/core/realtime-js/test/RealtimeClient.auth.resubscribe.test.ts]: Let's adjust this comments to either not exist, or be descriptive rather than referring to "bug", because it may seem arbitrary a year on from now.

File: packages/core/realtime-js/test/RealtimeClient.auth.resubscribe.test.ts [hunk 12]
```diff
@@ -0,0 +1,192 @@
...
+    expect(secondJoinCall![0].payload).toHaveProperty('access_token', customToken)
+  })
+
+  test('WORKAROUND: using accessToken callback works for resubscribe', async () => {
```
Comment (mandarini) [inline packages/core/realtime-js/test/RealtimeClient.auth.resubscribe.test.ts]: Again, here, "workaround" would refer to the "Specific" bug we're fixing, so I would rather not contain words that are describing a specific issue, but rather explain a behaviour. It will be easier for long term maintainability for new contributors to get context.

File: packages/core/realtime-js/test/RealtimeClient.auth.resubscribe.test.ts [hunk 13]
```diff
@@ -0,0 +1,192 @@
...
+    // This test shows that the workaround (using accessToken callback) works
```
Comment (mandarini) [inline packages/core/realtime-js/test/RealtimeClient.auth.resubscribe.test.ts]: Same as above

File: packages/core/realtime-js/test/RealtimeClient.auth.resubscribe.test.ts [hunk 14]
```diff
@@ -0,0 +1,192 @@
...
+    const channel2 = clientWithCallback.socket.channel('conversation:test', {
+      config: { private: true },
+    })
+
+    channel2.state = CHANNEL_STATES.closed
+    await channel2.subscribe()
+
+    const secondJoin = pushSpy.mock.calls.find((call) => call[0]?.event === 'phx_join')
+
+    // With accessToken callback, this WORKS
```
Comment (mandarini) [inline packages/core/realtime-js/test/RealtimeClient.auth.resubscribe.test.ts]: maybe remove this comment?

File: packages/core/realtime-js/src/RealtimeChannel.ts [hunk 15]
```diff
@@ -308,7 +308,11 @@ export default class RealtimeChannel {
...
+          // Only refresh if token wasn't manually set via setAuth(token)
+          if (!this.socket['_manuallySetToken']) {
```
Comment (mandarini) [inline packages/core/realtime-js/src/RealtimeChannel.ts]: I do not really like accessing private members like that. Can we please add a getter? Or a helper method like `isManualTokenSet(): boolean`?

Comment (reckziegelwilliam) [reply packages/core/realtime-js/src/RealtimeChannel.ts]: @mandarini yes

**Comment by reckziegelwilliam** [comment]
@mandarini ill proceed with your notes. Thank you for the review.

File: packages/core/realtime-js/test/RealtimeChannel.lifecycle.test.ts (hunk 7 above)
Comment (reckziegelwilliam) [reply packages/core/realtime-js/test/RealtimeChannel.lifecycle.test.ts]: Resolved. This was an IDE error on my end.

**Comment by filipecabaco** [comment]
thank you @reckziegelwilliam 🙏

**Comment by reckziegelwilliam** [comment]
@filipecabaco my pleasure! Always willing to support moving forward
