### PR TITLE
 fix(storage): set correct content-type for uploads

### LINKED ISSUE #2207: Storage upload fails with 415 when Content-Type is set in global headers
## Description

When `Content-Type` is set in `global.headers` during client initialization, file uploads fail with a 415 error. The outgoing request ends up with a malformed `Content-Type` header that combines the global value with the upload's own content type:

```
Content-Type: application/json, image/png
```

This was previously tolerated by the Storage API but https://github.com/supabase/storage/pull/893 introduced strict content header checking with the fastify version update (see [changelog](https://github.com/fastify/fastify/releases/tag/v5.7.2) "Parsing of the content-type header has been improved to a strict parser").

## Expected Behavior

The upload-specific content type should be sent as the sole `Content-Type` header value.

## Actual Behavior

The outgoing request contains both values joined as a single header.

```
Content-Type: application/json, image/png
```

### Steps to reproduce

```ts
import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = 'https://project.supabase.co'
const SUPABASE_ANON_KEY = 'anon_key'
const BUCKET = 'bucket-name'

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  global: {
    headers: {
      'Content-Type': 'application/json',
    },
    fetch: (url, init) => {
      console.log('Headers being sent:', init?.headers)
      return fetch(url, init)
    },
  },
})

const fileBuffer = Buffer.from('fake image content')

const { data, error } = await supabase.storage
  .from(BUCKET)
  .upload(`test-${Date.now()}.png`, fileBuffer, {
    contentType: 'image/png',
    upsert: true,
  })

if (error) {
  console.error('Upload failed:', error.message)
  console.error('Status:', error.status, '/ statusCode:', error.statusCode)
} else {
  console.log('Upload succeeded:', data)
}
```

Result:
```
Headers being sent: Headers {
  'X-Client-Info': 'supabase-js-node/2.101.0',
  'Content-Type': 'application/json, image/png',
  'x-upsert': 'true',
  'cache-control': 'max-age=3600',
  apikey: 'REDACTED',
  Authorization: 'Bearer REDACTED'
}
Upload failed: Invalid Content-Type header
Status: 400 / statusCode: 415
```

### System Info

```shell
System:
    OS: macOS 15.5
    CPU: (10) arm64 Apple M4
    Memory: 371.64 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.19.6 - /Users/kostas/.nvm/versions/node/v20.19.6/bin/node
    npm: 10.8.2 - /Users/kostas/.nvm/versions/node/v20.19.6/bin/npm
    pnpm: 10.32.1 - /Users/kostas/.nvm/versions/node/v20.19.6/bin/pnpm
    Deno: 2.6.9 - /opt/homebrew/bin/deno
  Browsers:
    Brave Browser: 146.1.88.132
    Chrome: 146.0.7680.165
    Firefox: 149.0
    Safari: 18.5
  npmPackages:
    @supabase/supabase-js: ^2.101.0 => 2.101.0
```

### Used Package Manager

npm

### Logs

```
Headers being sent: Headers {
  'X-Client-Info': 'supabase-js-node/2.101.0',
  'Content-Type': 'application/json, image/png',
  'x-upsert': 'true',
  'cache-control': 'max-age=3600',
  apikey: 'REDACTED',
  Authorization: 'Bearer REDACTED'
}
Upload failed: Invalid Content-Type header
Status: 400 / statusCode: 415
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/supabase/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/supabase/supabase-js/blob/master/CONTRIBUTING.md).
- [x] Read the [docs](https://supabase.com/docs/reference/javascript/introduction).
- [x] Check that there isn't [already an issue](https://github.com/supabase/supabase-js/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a Supabase JS Library issue and not an issue with the Supabase platform. If it's a Supabase platform related bug, it should likely be reported to [supabase/supabase](https://github.com/supabase/supabase) instead.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/supabase/supabase-js/discussions) or join our [Discord Chat Server](https://discord.supabase.com//).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by mandarini**
Moved from https://github.com/supabase/supabase-js/pull/2209

### What changed?

- In `BaseApiClient`, all header keys are now normalized to lowercase at initialization time, and `setHeader` also lowercases the key before storing
- Added 2 unit tests to `storageFileApi.test.ts` verifying that `upload` and `uploadToSignedUrl` correctly use the file-specific `contentType` over any globally configured `Content-Type` header

### Why was this change needed?

When users configure a global `Content-Type` header on the Supabase client (e.g. `'Content-Type': 'application/json'`), storage upload requests ended up with two conflicting header entries because the global header key and the upload-specific key had different casing. Since JavaScript object keys are case-sensitive, `Content-Type` and `content-type` were treated as distinct keys and both were sent in the request.

Lowercasing all header keys at storage time ensures that when the upload sets `content-type: image/png`, it overwrites the global `Content-Type: application/json` entry rather than sitting alongside it.

Closes #2207

## Screenshots/Examples

Before (broken):
```ts
const supabase = createClient(url, key, {
  global: { headers: { 'Content-Type': 'application/json' } }
})

// Would send both Content-Type: application/json AND content-type: image/png
await supabase.storage.from('bucket').upload('path', file, { contentType: 'image/png' })
```

After (fixed): the upload correctly sends only `content-type: image/png`.

## Breaking changes

- [ ] This PR contains no breaking changes

## Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/supabase/supabase-js/blob/master/CONTRIBUTING.md)
- [x] My PR title follows the [conventional commit format](https://www.conventionalcommits.org/): `<type>(<scope>): <description>`
- [x] I have run `npx nx format` to ensure consistent code formatting
- [x] I have added tests for new functionality (if applicable)
- [ ] I have updated documentation (if applicable)

## Additional notes

The fix applies case normalization at the storage client layer (`BaseApiClient`), so any header key variant (`Content-Type`, `content-type`, `CONTENT-TYPE`) is stored uniformly as lowercase. This is consistent with how HTTP headers are defined to be case-insensitive.

### CODE REVIEW

**Comment by mandarini** [comment]
@7ttp can you please rebase with `master`, for some reason it's not letting me

File: packages/core/storage-js/src/lib/common/BaseApiClient.ts [hunk 1]
```diff
@@ -30,7 +30,7 @@ export default abstract class BaseApiClient<TError extends StorageError = Storag
     namespace: ErrorNamespace = 'storage'
   ) {
     this.url = url
-    this.headers = headers
+    this.headers = Object.fromEntries(Object.entries(headers).map(([k, v]) => [k.toLowerCase(), v]))
```
Comment (ferhatelmas) [inline packages/core/storage-js/src/lib/common/BaseApiClient.ts:33]: I think this will regress vector client because constructor sets content-type to lower case but isPlainObject checks adds upper case content-type (they are different keys in the object). Fetch will normalize headers and will send two values for it but content-type is supposed to be a single value

Comment (mandarini) [reply packages/core/storage-js/src/lib/common/BaseApiClient.ts:33]: @7ttp can you please take a look here?

Comment (7ttp) [reply packages/core/storage-js/src/lib/common/BaseApiClient.ts:33]: > I think this will regress vector client because constructor sets content-type to lower case but isPlainObject checks adds upper case content-type they are different keys in the object Fetch will normalize headers and will send two values for it but content-type is supposed to be a single value

def makes sense 

> @7ttp can you please take a look here

i think we can keep this one as is and instead make the header set and merge points case insensitive for single value headers like `Content-Type`

that should kinda preserve this while avoiding the regress\ path where both `content-type` and `Content-Type` can exist on the same headers object before `fetch` normalizes them.....



wdyt/?
(if this somewhat makes sense i can get a small follow up pr  for it)

Comment (mandarini) [reply packages/core/storage-js/src/lib/common/BaseApiClient.ts:33]: yes can you please create a follow up PR? @7ttp

Comment (mandarini) [reply packages/core/storage-js/src/lib/common/BaseApiClient.ts:33]: @ferhatelmas here's the PR: https://github.com/supabase/supabase-js/pull/2220
